<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */ ?>

<?php $_product = $this->getProduct(); ?>

<?php
// GravDept:
// Moved to: /catalog/product/view/availability.phtml
?>
<?php /*if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
    	<div class="availability in-stock"><?php echo $this->__('In Stock') ?></div>
    <?php else: ?>
    	<div class="availability out-of-stock"><?php echo $this->__('Out Of Stock') ?></div>
    <?php endif; ?>
<?php endif;*/ ?>

<?php echo $this->getChildHtml('product_type_data_extra'); ?>

<?php echo $this->getPriceHtml($_product); ?>
