<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php
/**
 * Grouped product data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 * @see Mage_Catalog_Block_Product_View_Type_Grouped
 */
?>

<?php $this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<?php
// GravDept:
// Moved to: /catalog/product/view/availability.phtml
?>
<?php /*if ($this->displayProductStockStatus()): ?>
	<?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
		<div class="availability in-stock"><?php echo $this->__('In Stock') ?></div>
	<?php else: ?>
		<div class="availability out-of-stock"><?php echo $this->__('Out Of Stock') ?></div>
	<?php endif; ?>
<?php endif;*/ ?>

<?php echo $this->getChildHtml('product_type_data_extra') ?>

<table id="grouped-product-table" class="data-table">
	<thead>
		<tr>
			<th><?php echo $this->__('Product'); ?></th>
			
			<?php if ($this->getCanShowProductPrice($_product)): ?>
				<th><?php echo $this->__('Price'); ?></th>
			<?php endif; ?>
			
			<?php if ($_product->isSaleable()): ?>
				<th><?php echo $this->__('Quantity'); ?></th>
			<?php endif; ?>
		</tr>
	</thead>
	
	<tbody>
		<?php if ($_hasAssociatedProducts): ?>
			<?php foreach ($_associatedProducts as $_item): ?>
				<?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
				<tr>
					<td><?php echo $this->escapeHtml($_item->getName()) ?></td>
					
					<?php if ($this->getCanShowProductPrice($_product)): ?>
						<td>
							<?php if ($this->getCanShowProductPrice($_item)): ?>
								<?php echo $this->getPriceHtml($_item, true) ?>
								<?php echo $this->getTierPriceHtml($_item) ?>
							<?php endif; ?>
						</td>
					<?php endif; ?>
					
					<?php if ($_product->isSaleable()): ?>
						<td>
							<?php if ($_item->isSaleable()) : ?>
								<input type="text" name="super_group[<?php echo $_item->getId() ?>]" value="<?php echo $_item->getQty()*1 ?>" class="input-text qty" />
							<?php else: ?>
								<div class="availability out-of-stock"><?php echo $this->__('Out Of Stock') ?></div>
							<?php endif; ?>
						</td>
					<?php endif; ?>
				</tr>
			<?php endforeach; ?>
		<?php else: ?>
		   <tr>
			   <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('This product has no options.') ?></td>
		   </tr>
		<?php endif; ?>
	</tbody>
</table>
