<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
    <?php if ($this->isStepComplete('payment')): ?>
        <div class="opc-progress-step-title complete">
            <?php echo $this->__('Payment Method'); ?>
            <a href="#payment" class="button button-micro button-subtle" onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Edit'); ?></a>
        </div>

        <div class="opc-progress-step-content complete">
            <?php echo $this->getPaymentHtml(); ?>
        </div>
    <?php else: ?>
        <div class="opc-progress-step-title incomplete">
            <?php echo $this->__('Payment Method'); ?>
        </div>

        <div class="opc-progress-step-content incomplete">
            <?php echo $this->__('Pending'); ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
