<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php $_orders = $this->getOrders(); ?>

<h1><?php echo $this->__('Order History') ?></h1>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($_orders->getSize()): ?>
	<table id="order-history-table" class="flex-table">
		
		<thead>
			<tr>
    			<th><?php echo $this->__('Order #') ?></th>
    			<th class="nowrap"><?php echo $this->__('Date') ?></th>
				<th><?php echo $this->__('Recipient') ?></th>
				<th><?php echo $this->__('Total') ?></th>
				<th><?php echo $this->__('Status') ?></th>
				<?php /*<th class="a-right"><?php echo $this->__('Tracking') ?></th>*/ ?>
				<th><?php echo $this->__('Details') ?></th>
			</tr>
		</thead>
		
		<tbody>
			<?php foreach ($_orders as $_order): ?>
				<tr>
					
					<td><?php echo $_order->getRealOrderId() ?></td>
					<td class="nowrap"><?php echo $this->formatDate($_order->getCreatedAtStoreDate(), 'medium') ?></td>
					<td><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
					<td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
					<?php /*<td class="a-right"><a class="button button-small button-subtle" href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a></td>*/ ?>
					<td><?php echo $_order->getStatusLabel() ?></td>
					<td><a class="button button-small" href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View') ?></a></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	
	<div class="toolbar">
    	<?php echo $this->getPagerHtml(); ?>
	</div>
<?php else: ?>
	<p><?php echo $this->__('You have not placed an order.') ?></p>
<?php endif ?>
