<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com All rights reserved.
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>

<?php $_order = $this->getOrder() ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="page-title">
    <h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
    
    <div class="order-view-actions">
        <?php echo $this->getChildHtml('buttons') ?>
    </div>
</div>

<?php echo $this->getStatusHistoryRssUrl($_order) ?>

<div class="block order-info">
    <div class="block-title">
        <h2><?php echo $this->__('Order Information') ?></h2>
    </div>
    
    <div class="block-content lined">
        <div id="order-view-details" class="grid">
        	<div class="grid_2 alpha">
        		<h3><?php echo $this->__('Date') ?></h3>
        		<p><?php echo $this->formatDate($_order->getCreatedAtStoreDate(), 'long') ?></p>
        		
        		<h3><?php echo $this->__('Status') ?></h3>
        		<p><?php echo $_order->getStatusLabel() ?></p>
        	</div>
            
            <?php if (!$_order->getIsVirtual()): ?>
            	<div class="grid_3">
            		<h3><?php echo $this->__('Shipping Address') ?></h3>
            		
            		<address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            	
            		<h3><?php echo $this->__('Shipping Method') ?></h3>
            		
            		<p>
            			<?php if ($_order->getShippingDescription()): ?>
            			    <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
            			<?php else: ?>
            			    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
            			<?php endif; ?>
            			
            			<?php if ($_order->getTracksCollection()->count()) : ?>
            				<br/><a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopUpUrlByOrderId($_order->getId()) ?>','trackorder','top=50,left=50,width=800,height=600,resizable=yes,scrollbars=yes'); return false;"><?php echo $this->__('Tracking Info') ?></a>
            			<?php endif; ?>
            		</p>
            	</div>
            <?php endif; ?>
            
            <div class="grid_4">
            	<h3><?php echo $this->__('Billing Address') ?></h3>
            	<address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            
            	<h3><?php echo $this->__('Payment Method') ?></h3>
            	<?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>


<?php
// GravDept
// tabs for: items, invoice, shipment, creditmemo
// not included because lots of duplicate content is confusing

/*
<?php $_links = $this->getLinks(); ?>

<ul id="order-info-tabs">
    <?php foreach ($_links as $_link): ?>
        <?php if($_link->getUrl()): ?>
            <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
        <?php else: ?>
            <li class="current"><?php echo $_link->getLabel() ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
*/
?>
