<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<div class="order-items order-details">
	<?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('items', $this->getOrder())): ?>
		<script type="text/javascript">
		//<![CDATA[
		function giftMessageToogle(giftMessageIdentifier)
		{
			var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
			var container = $('order-item-gift-message-'+giftMessageIdentifier);
			var row = $('order-item-row-'+giftMessageIdentifier);
			if(link.expanded) {
				link.expanded = false;
				link.removeClassName('expanded');
				if(container.hasClassName('last')) {
					row.addClassName('last');
				}
				container.hide();
			} else {
				link.expanded = true;
				link.addClassName('expanded');
				if(container.hasClassName('last')) {
					row.removeClassName('last');
				}
				container.show();
			}
		
			return false;
		}
		//]]>
		</script>
	<?php endif; ?>
	
	<?php $_order = $this->getOrder() ?>
	
	<?php
	// GravDept:
	// Moved to: /sales/order/info.phtml
	?>
	<?php /*
	<h3>
		<?php echo $this->__('Items Ordered') ?>
		<?php if ($_order->getTracksCollection()->count()) : ?>
			<span class="separator">|</span> <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;"><?php echo $this->__('Track your order') ?></a>
		<?php endif; ?>
	</h3>
	*/ ?>

	<?php echo $this->getChildHtml('order_items') ?>

	<?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
		<div class="order-additional order-gift-message">
			<h3><?php echo $this->__('Gift Messages') ?></h3>
			
			<?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
			
			<dl class="gift-message-history">
				<dt>
					<strong><?php echo $this->__('From:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?><br />
					<strong><?php echo $this->__('To:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?>
				</dt>
				<dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
			</dl>
		</div>
	<?php endif; ?>
	
	<?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
	
	<?php if (count($_history)): ?>
		<div class="order-additional order-comments">
			<h3><?php echo $this->__('About Your Order') ?></h3>
			
			<dl class="order-about">
				<?php foreach ($_history as $_historyItem): ?>
					<dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
					<dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
				<?php endforeach; ?>
			</dl>
		</div>
	<?php endif; ?>
</div>
