<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<?php if (!empty($count)):?>
	<a href="#customer-reviews"><?php echo $this->__('%s Review(s)', $count) ?></a>
<?php endif;?>
