<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php $_items = $this->getReviewsCollection()->getItems(); ?>

<div id="customer-reviews" class="block">
    <div class="block-title">
    	<h2><?php echo $this->__('Customer Reviews') ?></h2>
    </div>
    
    <div class="block-content">
    	<?php if (count($_items)): ?>
    		<?php echo $this->getChildHtml('toolbar') ?>
    		
    		<ol class="reviews">
    			<?php foreach ($_items as $_review):?>
    				<li>
    					<?php $_votes = $_review->getRatingVotes(); ?>
    					
    					<?php if (count($_votes)): ?>
    
    						<?php foreach ($_votes as $_vote): ?>
    							<div class="rating-box">
    								<div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
    							</div>
    							<?php break;  /* GravDept custom, end after one */ ?>
    						<?php endforeach; ?>
    						
    						<?php /*
    						<table class="ratings-table">
    							<tbody>
    								<?php foreach ($_votes as $_vote): ?>
    									<tr>
    										<th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
    										<td>
    											<div class="rating-box">
    												<div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
    											</div>
    										</td>
    									</tr>
    								<?php endforeach; ?>
    							</tbody>
    						</table>
    						*/ ?>
    						
    					<?php endif; ?>
    					
    					<?php /*<h3><a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $this->escapeHtml($_review->getTitle()) ?></a></h3>*/  /* link fails on product page */ ?>
    					<h3><?php echo $this->escapeHtml($_review->getTitle()) ?></h3>
    					
    					
    					<p class="written">
    						<?php echo $this->__('by') ?>
    						<?php echo $this->escapeHtml($_review->getNickname()) ?>
    						<?php echo $this->__('on') ?>
    						<?php echo $this->formatDate($_review->getCreatedAt(), 'medium') ?>
    					</p>
    					
    					<div class="review-body">
    						<?php echo nl2br($this->escapeHtml($_review->getDetail())) ?>
    					</div>
    				</li>
    			<?php endforeach; ?>
    		</ol>
    		
    		<a class="button" href="#review-form"><?php echo $this->__('Write A Review') ?></a>
    		
    		<?php /*if (count($_items) > 10): ?>
    			<a class="button" href="#"><?php echo $this->__('More Reviews') ?></a>
    		<?php endif;*/ ?>
    		
    		<?php /*echo $this->getChildHtml('toolbar')*/ ?>
    	<?php else: ?>    
    	    <div class="block-content lined">
        		<p class="no-reviews"><?php echo $this->__('This product has not been reviewed. You could write the first review.') ?></p>
        	</div>
    	<?php endif; ?>
    </div>
</div>