<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<?php /* also used for tag search, see customization in /app/code/local/Tag/Block/Product/Result.php */ ?>
<div class="grid-block">
	<h1><?php echo ($this->getHeaderText() || $this->getHeaderText() === false) ? $this->getHeaderText() : $this->__("Searched: %s", $this->helper('catalogsearch')->getEscapedQueryText()) ?></h1>
</div>
