<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php
/**
 * Template for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>

<h1><?php echo $this->__('Address Book') ?></h1>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="address-book-new">
	<h2><?php echo $this->__('Create New Address') ?></h2>
	<a class="button" href="<?php echo $this->getAddAddressUrl() ?>"><?php echo $this->__('Add Address') ?></a>
</div>

<div id="address-book" class="grid">	
	<div class="grid_3 alpha">
		<div class="address-box">
			<h2><?php echo $this->__('Billing Default') ?></h2>
			
			<?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
				<address><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></address>
				<a class="button button-small button-subtle" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Edit') ?></a>
			<?php elseif($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
				<address><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></address>
				<a class="button button-small button-subtle" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Edit') ?></a>
			<?php else: ?>
				<address><?php echo $this->__('You haven\'t chosen a default billing address.') ?></p>
			<?php endif ?>
		</div>
	</div>
	
	<div class="grid_3">
		<div class="address-box">
			<h2><?php echo $this->__('Shipping Default') ?></h2>
			
			<?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
				<address><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></address>
				<a class="button button-small button-subtle" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Edit') ?></a>
			<?php elseif($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
				<address><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></address>
				<a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Edit') ?></a>
			<?php else: ?>
				<p><?php echo $this->__('You haven\'t chosen a default shipping address.') ?></p>
			<?php endif ?>
		</div>
	</div>
	
	<?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
		<div class="grid_4 omega address-additional">
			<h2><?php echo $this->__('Additional Addresses') ?></h2>
		
			<ol>
				<?php foreach($_pAddsses as $_address): ?>
					<li>
						<address><?php echo $this->getAddressHtml($_address) ?></address>
						<a class="button button-small button-subtle" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit') ?></a>
						<a class="button button-small button-subtle" href="#" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete') ?></a>
					</li>
				<?php endforeach; ?>
			</ol>
		</div>
	<?php endif ?>
</div>

<script type="text/javascript">
	//<![CDATA[
		function deleteAddress(addressId) {
			if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
				window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
			}
			return false;
		}
//]]>
</script>
