<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2013 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.5
 */
?>

<?php
// GravDept:
// Custom template based on: /app/design/frontend/base/default/template/catalog/product/new.phtml
?>

<?php $_products = $this->getProductCollection() ?>
<?php $_collectionSize = $_products->getSize(); ?>

<?php if( $_collectionSize === 0): ?>

	<h2><?php echo ($this->getLabel()) ? $this->getLabel() : $this->__('New Products') ?></h2>
	<p><?php echo $this->__('No products found.') ?></p>
	
<?php else: ?>
	
	<?php /* GravDept, set column count from XML layout or CMS Page template tags (default:2) */ ?>
	<?php $_columnCount = $this->getColumnCount(); ?>
	
	<?php /* GravDept, set column count manually here */ ?>
	<?php /*$_columnCount = 4;*/ ?>
	
	<div class="product-slider cols_<?php echo $_columnCount; ?>">
		<h2><?php echo $this->__('New Products') ?></h2>
		
		<?php if ( $_collectionSize > $_columnCount ): ?>
			<div class="slides-controls">
				<a href="#" title="<?php echo $this->__('Previous') ?>" class="prev"><?php echo $this->__('Previous') ?></a>
				<a href="#" title="<?php echo $this->__('Next') ?>" class="next"><?php echo $this->__('Next') ?></a>
			</div>
		<?php endif; ?>
		
		<div class="slides-container">
			<?php $i=0; ?>
			
			<?php foreach ($_products->getItems() as $_product): ?>
			
				<?php if ($i++%$_columnCount==0): ?>
					<div class="slide">
						<ul class="slide-product-list">
				<?php endif; ?>
				            
				            <?php
				            /* GravDept. Get data to check if product is new. */
				            $gravdept_now = date("Y-m-d");
				            $gravdept_newFrom = substr($_product->getNewsFromDate(), 0, 10);
				            $gravdept_newTo = substr($_product->getNewsToDate(), 0, 10);
				            ?>
				            
							<li>
							    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
								    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200) ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
								    
								    <?php /* GravDept. Check if product is new. */ ?>
								    <?php if ( $gravdept_now >= $gravdept_newFrom && $gravdept_now <= $gravdept_newTo ): ?>
								        <div class="is-new-product">New</div>
								    <?php endif; ?>
								    
								    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								</a>
								
								<a class="product-name" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a>
								
								<?php echo $this->getPriceHtml($_product, true, '-new') ?>
								
								<?php /*
								<?php if($_product->isSaleable()): ?>
									<button class="faux-button" href="<?php echo $this->getAddToCartUrl($_product) ?>"><?php echo $this->__('Add To Cart') ?></a>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out Of Stock') ?></span></p>
								<?php endif; ?>
							
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add To Wishlist') ?></a>
								<?php endif; ?>
								
								<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
									<a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add To Compare') ?></a>
								<?php endif; ?>
								*/ ?>
							</li>
				
				<?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
						</ul>
					</div><?php /* END .slide */ ?>
				<?php endif ?>
			<?php endforeach; ?>
		</div>
	</div>
	
<?php endif; ?>
