<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<div class="grid-block">
	<h1><?php echo $this->__('All Tags') ?></h1>
	
	<?php if( sizeof($this->getTags()) > 0 ): ?>
		<ul class="tags-list">
			<?php foreach ($this->getTags() as $_tag): ?>
				<li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" <?php /* style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;" */ ?>><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
			<?php endforeach; ?>
		</ul>
	<?php else: ?>
		<p><?php echo $this->__("No products have been tagged yet.") ?></p>
	<?php endif; ?>
</div>