<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<div class="block block-tags">
    <div class="block-title">
        <h2><?php echo $this->__('Popular Tags'); ?></h2>
    </div>
    
    <div class="block-content lined">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" <?php /* style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;" */ ?>><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>

        <div class="actions">
            <a class="view-all-tags button button-micro button-subtle" href="<?php echo $this->getUrl('tag/list') ?>"><?php echo $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
