<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2014 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.6
 */
?>

<!DOCTYPE html>
<?php echo $this->getChildHtml('gravdept_html') ?>

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body class="<?php echo $this->getBodyClass() ? $this->getBodyClass() : ''; ?>">

	<?php echo $this->getChildHtml('after_body_start') ?>
	<?php echo $this->getChildHtml('global_notices') ?>
	
	<div id="wrapper">
		<div id="container">
			<?php echo $this->getChildHtml('header') ?>
		    
		    <div id="matter" class="matter">
			    <?php echo $this->getChildHtml('breadcrumbs') ?>
			    
			    <?php /* GravDept custom */ ?>
				<?php echo $this->getChildHtml('gravdept_titleBanner') ?>
				
				<div class="grid">
					<div id="catalog-layered-sidebar" class="grid_3">
						<?php echo $this->getChildHtml('left') ?>
						
						<?php if ( $this->getChildHtml('snippet_catalog_sidebar_below') ): ?>
						    <div class="snippet snippet-catalog-sidebar-below"><?php echo $this->getChildHtml('snippet_catalog_sidebar_below') ?></div>
						<?php endif; ?>
					</div>
					
					<div id="catalog-layered-list" class="grid_9">
						<?php echo $this->getChildHtml('global_messages') ?>
						
						<?php echo $this->getChildHtml('content') ?>
					</div>
				</div>
			</div>
		
			<?php echo $this->getChildHtml('footer') ?>
		</div>
	</div>
	
	<?php echo $this->getChildHtml('global_cookie_notice') ?>
	<?php echo $this->getChildHtml('before_body_end') ?>
	<?php echo $this->getAbsoluteFooter() ?>

</body>
</html>
