<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2014 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.6
 */
?>

<!DOCTYPE html>
<?php echo $this->getChildHtml('gravdept_html') ?>

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body class="<?php echo $this->getBodyClass() ? $this->getBodyClass() : ''; ?>">

	<?php echo $this->getChildHtml('after_body_start') ?>
	<?php echo $this->getChildHtml('global_notices') ?>
	
	<div id="wrapper">
		<div id="container">
			<?php echo $this->getChildHtml('header') ?>
		
			<div id="matter" class="matter">
			    <?php echo $this->getChildHtml('breadcrumbs') ?>
			    
				<div class="grid-block">
					<h1><?php echo $this->__('Checkout') ?></h1>
					
					<?php echo $this->getChildHtml('global_messages') ?>
				</div>
				
				<?php if ( $this->getChildHtml('snippet_checkout_onepage_top') ): ?>
				    <div class="snippet snippet-checkout-onepage-top"><?php echo $this->getChildHtml('snippet_checkout_onepage_top') ?></div>
				<?php endif; ?>
				
				<div class="grid">
					<div class="grid_8">
						<?php echo $this->getChildHtml('content') ?>
						
						<?php if ( $this->getChildHtml('snippet_checkout_onepage_steps_below') ): ?>
						    <div class="snippet snippet-checkout-onepage-steps-below"><?php echo $this->getChildHtml('snippet_checkout_onepage_steps_below') ?></div>
						<?php endif; ?>
					</div>
					
					<div id="opc-progress-wrapper" class="grid_4">
						<?php echo $this->getChildHtml('right') ?>
						
						<?php if ( $this->getChildHtml('snippet_checkout_onepage_progress_below') ): ?>
						    <div class="snippet snippet-checkout-onepage-progress-below"><?php echo $this->getChildHtml('snippet_checkout_onepage_progress_below') ?></div>
						<?php endif; ?>
					</div>
				</div>
			</div>
		
			<?php echo $this->getChildHtml('footer') ?>
		</div>
	</div>
	
	<?php echo $this->getChildHtml('global_cookie_notice') ?>
	<?php echo $this->getChildHtml('before_body_end') ?>
	<?php echo $this->getAbsoluteFooter() ?>

</body>
</html>
