<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<form id="co-shipping-form" class="stack-form" action="">
	<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
	
	<?php if ($this->customerHasAddresses()): ?>
		<ul class="form-list">
			<li>
				<label for="shipping-address-select"><?php echo $this->__('Select from your address book or create a new address') ?></label>
				
				<div class="input-box">
				    <?php echo $this->getAddressesHtmlSelect('shipping') ?>
				</div>
			</li>
		</ul>
	<?php endif ?>
	
	<ul class="form-list" id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>

		<li class="fields">
		    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
		</li>
		
		<li>
			<label for="shipping:company"><?php echo $this->__('Company') ?></label>
			
			<div class="input-box">
    			<input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
    		</div>
		</li>
		
		<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
		<li>
			<label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Street') ?> 1</label>
			
			<div class="input-box">
				<input type="text" name="shipping[street][]" id="shipping:street1" title="<?php echo $this->__('Street') ?> 1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
		    </div>
		</li>
		
		<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
			<li>
				<label for="shipping:street<?php echo $_i ?>"><?php echo $this->__('Street') ?> <?php echo $_i ?></label>
				
				<div class="input-box">
					<input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
			    </div>
			</li>
		<?php endfor; ?>
		
		<?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
            <li>
                <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                
                <div class="input-box">
                    <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                </div>
            </li>
        <?php endif; ?>
		
		<li>
			<label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
			
			<div class="input-box">
				<input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" title="<?php echo $this->__('City') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
		    </div>
		</li>
		
		<li>
			<label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
			
			<div class="input-box">
    			<select id="shipping:region_id" name="shipping[region_id]" class="validate-select" style="display:none;">
    				<option value=""><?php echo $this->__('Please select state, region, or province') ?></option>
    			</select>
    			
    			<script type="text/javascript">
    				$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
    			</script>
    			
    			<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
    		</div>
		</li>
		
		<li>
			<label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
			
			<div class="input-box">
				<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" title="<?php echo $this->__('Zip/Postal Code') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
			</div>
		</li>
		
		<li>
			<label for="shipping:country_id"><?php echo $this->__('Country') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			
			<div class="input-box">
				<?php echo $this->getCountryHtmlSelect('shipping') ?>
			</div>
		</li>
		
		<li>
			<label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Phone') ?></label>
			
			<div class="input-box">
				<input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
		    </div>
		</li>
		
		<li>
			<label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
			
			<div class="input-box">
				<input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
			</div>
		</li>
		
		<li class="controls">
			<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
				<div class="control">
				    <input type="checkbox" name="shipping[save_in_address_book]" value="1" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
				    <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
				</div>
			<?php else: ?>
				<input type="hidden" name="shipping[save_in_address_book]" value="1" />
			<?php endif; ?>
    		
    		<div class="control">
    			<input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" />
    			<label for="shipping:same_as_billing"><?php echo $this->__('Nevermind, use Billing Address instead') ?></label>
    		</div>
		</li>
		
	</ul>

	<div id="shipping-buttons-container" class="buttons-set">
		<button class="button" onclick="shipping.save()"><?php echo $this->__('Continue') ?></button>
		<span class="please-wait" id="shipping-please-wait" style="display:none;"><?php echo $this->__('Loading') ?></span>
	</div>

</form>

<script type="text/javascript">
	//<![CDATA[
		var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
			'<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
		var shippingForm = new VarienForm('co-shipping-form');
		shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
		//shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
		$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
	
		var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
	//]]>
</script>
