<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<h1><?php echo $this->__('Account Overview'); ?></h1>

<h2><?php echo $this->__('Hello %s, it&rsquo;s nice to see you!', $this->escapeHtml(Mage::getSingleton('customer/session')->getCustomer()->getFirstname())); ?></h2>
<?php /*echo $this->__('Hello %s!', $this->escapeHtml($this->getCustomerName()));*/ ?>