<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<div id="dashboard-account-info" class="grid">
	<div class="grid_2 alpha">
		<h3><?php echo $this->__('Account Info') ?></h3>
		<a class="button button-small button-subtle" href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
	</div>
	
	<div class="grid_8 omega">
		<dl>
			<dt><?php echo $this->__('Name') ?></dt>
			<dd><?php echo $this->escapeHtml($this->getCustomer()->getName()) ?></dd>
			
			<dt><?php echo $this->__('Email') ?></dt>
			<dd><?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?></dd>
			
			<dt><?php echo $this->__('Password') ?></dt>
			<dd><a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a></dd>
		</dl>
	</div>
</div>


<?php if( $this->isNewsletterEnabled() ): ?>
    <div id="dashboard-newsletter" class="grid">
        <div class="grid_2 alpha">
            <h3><?php echo $this->__('Newsletter') ?></h3>
            <a class="button button-small button-subtle" href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
        </div>
        
        <div class="grid_8 omega">
            <?php if( $this->getIsSubscribed() ): ?>
                <p><?php echo $this->__("You are subscribed to the newsletter.") ?></p>
            <?php else: ?>
                <p><?php echo $this->__('You are not subscribed.') ?></p>
                <p><?php echo $this->__('Subscribe to the newsletter to receive special offers and news via email.') ?></p>
            <?php endif; ?>
            
            <?php /* Extensions placeholder */ ?>
            <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
        </div>
    </div>
<?php endif; ?>
