<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<div id="dashboard-newsletter" class="grid">
	<div class="grid_2 alpha">
		<h3><?php echo $this->__('Newsletter') ?></h3>
		<a class="button button-small button-subtle" href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Manage') ?></a>
	</div>
	
	<div class="grid_8 omega">
		<h4><?php echo $this->__('Subscription') ?></h4>
		
		<?php if ( $this["_subscription (Mage_Newsletter_Model_Subscriber)"]["subscriber_status"] == 1 ):  /* does not work */ ?>
			<p><?php echo $this->__('You are subscribed to our newsletter.') ?></p>
		<?php else: ?>
			<p><?php echo $this->__('You are not subscribed to our newsletter.') ?></p>
		<?php endif; ?>
	</div>
</div>
