<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<div class="block block-popular-searches">
    <div class="block-title">
        <h2><?php echo $this->__('Popular Searches') ?></h2>
    </div>
    
    <div class="block-content lined">
        <?php if (sizeof($this->getTerms()) > 0): ?>
            <ul class="tags-list">
                <?php foreach ($this->getTerms() as $_term): ?>
                    <li><a href="<?php echo $this->getSearchUrl($_term) ?>" <?php /*style="font-size:<?php echo $_term->getRatio()*70+75 ?>%;"*/ ?>><?php echo $this->escapeHtml($_term->getName()) ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p class="note-msg"><?php echo $this->__('No search terms are available.'); ?></p>
        <?php endif; ?>
    </div>
</div>
