<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2013 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.5
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>

<?php $_productCollection=$this->getLoadedProductCollection() ?>

<?php if(!$_productCollection->count()): ?>

	<div class="catalog-no-results">
		<h2><?php echo $this->__('No items found.') ?></h2>
		<p><?php echo $this->__('Try searching or browse the categories.') ?></p>
	</div>
	
<?php else: ?>

	<div class="toolbar catalog-bar">
		<?php echo $this->getToolbarHtml() ?>
	</div>
	
	<?php if($this->getMode()!='grid'): /* List mode */ ?>
	
		<?php $_iterator = 0; ?>
		<ol class="product-list">
			<?php foreach ($_productCollection as $_product): ?>
				<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">

					<?php
					/* GravDept. Get data to check if product is new. */
					$gravdept_now = date("Y-m-d");
					$gravdept_newFrom = substr($_product->getNewsFromDate(), 0, 10);
					$gravdept_newTo = substr($_product->getNewsToDate(), 0, 10);
					?>
					
					<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getImageLabel($_product, 'small_image')) ?>">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel($_product, 'small_image')) ?>" />
					
					    <?php /* GravDept. Check if product is new. */ ?>
					    <?php if ( $gravdept_now >= $gravdept_newFrom && $gravdept_now <= $gravdept_newTo ): ?>
					        <div class="is-new-product">New</div>
					    <?php endif; ?>
					</a>
					
					<div class="product-details">
						<h2><a class="product-name" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName())?></a></h2>
						
						<?php if($_product->getRatingSummary()): ?>
							<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						
						<p class="description"><?php echo nl2br($_product->getShortDescription()) ?></p>
						
						<?php echo $this->getPriceHtml($_product, true) ?>
						
						<?php /*
						<?php if($_product->isSaleable()): ?>
							<button onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add To Cart') ?></button>
						<?php else: ?>
							<p class="availability"><span class="out-of-stock">Out Of Stock') ?></span></p>
						<?php endif; ?>
						
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add To Wish List') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add To Compare') ?></a></li>
							<?php endif; ?>
						</ul>
						*/ ?>
					</div>
					
				</li>
			<?php endforeach; ?>
		</ol>

	<?php else: /* Grid Mode */ ?>

		<?php $_collectionSize = $_productCollection->count() ?>
		
		<table class="product-grid">
			<?php $_columnCount = $this->getColumnCount(); // Set number of columns from XML layout ?>
			<?php /* $_columnCount = 4; // Set number of columns here */ ?>
			
			<?php $i=0; foreach ($_productCollection as $_product): ?>
			
				<?php if ($i++%$_columnCount==0): ?>
    				<tr>
				<?php endif ?>
				
        				<td>
        					<?php
        					/* GravDept. Get data to check if product is new. */
        					$gravdept_now = date("Y-m-d");
        					$gravdept_newFrom = substr($_product->getNewsFromDate(), 0, 10);
        					$gravdept_newTo = substr($_product->getNewsToDate(), 0, 10);
        					?>
        					
        					<a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
        					    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel($_product, 'small_image')) ?>" />
        					
        					    <?php /* GravDept. Check if product is new. */ ?>
        					    <?php if ( $gravdept_now >= $gravdept_newFrom && $gravdept_now <= $gravdept_newTo ): ?>
        					        <div class="is-new-product">New</div>
        					    <?php endif; ?>
        					    
        					    <?php if($_product->getRatingSummary()): ?>
        					    	<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
        					    <?php endif; ?>
        					</a>
        					
        					<h2><a class="product-name" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h2>
        					
        					<?php echo $this->getPriceHtml($_product, true) ?>
        					
        					<?php /*
        					<?php if($_product->isSaleable()): ?>
        						<button onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add To Cart') ?></button>
        					<?php else: ?>
        						<p class="availability"><span class="out-of-stock"><?php echo $this->__('Out Of Stock') ?></span></p>
        					<?php endif; ?>
        	
        					<ul class="add-to-links">
        						<?php if ($this->helper('wishlist')->isAllow()) : ?>
        							<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add To Wish List') ?></a></li>
        						<?php endif; ?>
        						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
        							<li><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add To Compare') ?></a></li>
        						<?php endif; ?>
        					</ul>
        					*/ ?>
        				</td>
				
				<?php if ($i%$_columnCount==0 && $i!=$_collectionSize): ?>
					</tr>
				<?php endif ?>
				
			<?php endforeach ?>
			
			<?php for($i;$i%$_columnCount!=0;$i++): ?>
				<td class="empty">&nbsp;</td>
			<?php endfor ?>
			
			<?php if ($i%$_columnCount==0): ?>
				</tr>
			<?php endif ?>
		</table>
		
	<?php endif; ?>
	
	<div class="toolbar pager-bar">
		<?php echo $this->getToolbarHtml() ?>
	</div>
		
<?php endif; ?>

<?php if ( $this->getChildHtml('snippet_catalog_list_below') ): ?>
    <div class="snippet snippet-catalog-list-below"><?php echo $this->getChildHtml('snippet_catalog_list_below') ?></div>
<?php endif; ?>
