<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
	<h2><?php echo $this->__('New Products'); ?></h2>
	
	<?php
	// GravDept:
	// Set column count from XML layout or CMS Page template tags.
	// Or set column count manually here.
	?>
	<?php $_columnCount = $this->getColumnCount(); ?>
	<?php /*$_columnCount = 4;*/ ?>
	
	<?php $i=0; ?>
	
	<?php foreach ($_products->getItems() as $_product): ?>
		<?php if ($i++%$_columnCount==0): ?>
			<ul class="new-products-list">
		<?php endif; ?>
	
				<li>
					<a class="product-image" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>" alt="<?php echo $this->escapeHtml($_product->getName()); ?>" /></a>
					<a class="product-name" href="<?php echo $_product->getProductUrl(); ?>"><?php echo $this->escapeHtml($_product->getName()); ?></a>
					
					<?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>
					<?php echo $this->getPriceHtml($_product, true, '-new'); ?>
					
					<?php /*
					<?php if($_product->isSaleable()): ?>
						<button class="button" href="<?php echo $this->getAddToCartUrl($_product) ?>"><?php echo $this->__('Add To Cart') ?></a>
					<?php else: ?>
						<p class="availability out-of-stock"><span><?php echo $this->__('Out Of Stock') ?></span></p>
					<?php endif; ?>
				
					<?php if ($this->helper('wishlist')->isAllow()) : ?>
						<a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add To Wishlist') ?></a>
					<?php endif; ?>
					
					<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
						<a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add To Compare') ?></a>
					<?php endif; ?>
					*/ ?>
				</li>
	
		<?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
			</ul>
		<?php endif; ?>
	<?php endforeach; ?>
<?php else: ?>
	<h2><?php echo $this->__('New Products'); ?></h2>
	<p><?php echo $this->__('No products found.'); ?></p>
<?php endif; ?>
