<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div class="grid-block">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div id="product-info" class="grid">
    <div id="product-overview" class="grid_7 push_5">
        <h1><?php echo $_helper->categoryAttribute($_product, $_product->getName(), 'name') ?></h1>
        
        <?php /* Rating + Reviews Link */ ?>
        <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
        
        <?php if ($_product->getShortDescription()): ?>
            <p class="short-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
        <?php endif; ?>
        
        <?php /* GravDept: moved from /downloadable/catalog/product/type.phtml */ ?>
        <?php echo $this->getChildHtml('samples') ?>
        
        <?php /* GravDept: custom reference for inventory status. */ ?>
        <?php echo $this->getChildHtml('availability') ?>
        
        <div class="pricing-wrapper">
            <?php /* Price Box */ ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            
            <?php /* Tier Prices. Magento new style. */ ?>
            <?php echo $this->getTierPriceHtml() ?>
            
            <?php /* Tier prices. GravDept. */ ?>
            <?php /*echo $this->getChildHtml('tierprices')*/ ?>
        </div>
        
        <?php echo $this->getChildHtml('alert_urls') ?>
        
        <?php /* Reviews (return to product link) */ ?>
        <?php echo $this->getChildHtml('other') ?>
        
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey'); ?>

            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />		
            
            <?php /* GravDept. Apparently nothing. */ ?>
            <?php echo $this->getChildHtml('extrahint') ?>
            
            <?php /* GravDept: duplicated from above. Probably can remove one. */ ?>
            <?php /*echo $this->getChildHtml('other')*/ ?>
            
            <?php
            // GravDept
            // Custom reference for grouped products only.
            // For simple/config/bundle products the 'product_type_data' template is inserted in {div.options} below.
            // Grouped products don't have a {.pricing-box} so this makes IA awkward.
            // This template is rendered before {.options} to hide that block using a CSS adjacent selector.
            ?>
            <?php echo $this->getChildHtml('product_type_data_grouped') ?>
            
            <?php /* GravDept: quantity input and configurable product options. */ ?>
            <div class="options">
                <?php /* GravDept custom: externalized quantity input. */ ?>
                <?php echo $this->getChildHtml('addquantity') ?>
                
                <?php /* GravDept note: shows product custom options (not configurable product options). */ ?>
                <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif; ?>
                
                <?php
                // GravDept note:
                // Shows configurable product options.
                // Shows buttons to update product configuration on wishlist.
                ?>
                <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif; ?>
            </div>
            
            <?php
            // GravDept
            // This is Magento default code, but it mixes too many things together.
            // Add to Compare/Wishlist buttons have been externalized.
            // Note: the 'extra_buttons' reference is not preserved. It's not clear what this does.
            ?>
            <?php /*
            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>
            */ ?>
            
            <div class="actions-block">
                <?php if($_product->isSaleable()): ?>
                    <?php echo $this->getChildHtml('addtocart') ?>
                <?php endif; ?>
            
                <ul class="alternate-actions">
                    <?php echo $this->getChildHtml('addtowishlist') ?>
                    
                    <?php
                    /* GravDept, removed from theme */
                    /*echo $this->getChildHtml('addtocompare')*/
                    ?>
                    
                    <?php if ($this->canEmailToFriend()): ?>
                        <li class="share-by-email"><a class="button button-small button-subtle" href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Share By Email') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </form>
        
        <script type="text/javascript">
            //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;
        
                        if (url) {
                           form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }
        
                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);
        
                productAddToCartForm.submitLight = function(button, url){
                    if(this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }
                        
                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
            //]]>
        </script>
        
        <div id="product-tabs" class="tabs">
            <ul class="tabs-nav">
                <li><a href="#tab-description"><?php echo $this->__('Description'); ?></a></li>
                
                <li><a href="#tab-details"><?php echo $this->__('Details'); ?></a></li>
                
                <li><a href="#tab-tags"><?php echo $this->__('Tags'); ?></a></li>
                
                <?php if ( $this->getChildHtml('snippet_product_view_tab_1') ): ?>
                    <li><a href="#tab-custom-1"><?php echo $this->__('Custom 1'); ?></a></li>
                <?php endif; ?>
                
                <?php if ( $this->getChildHtml('snippet_product_view_tab_2') ): ?>
                    <li><a href="#tab-custom-2"><?php echo $this->__('Custom 2'); ?></a></li>
                <?php endif; ?>
            </ul>
            
            <div class="tabs-content">
                <div id="tab-description">
                    <?php echo $this->getChildHtml('description'); ?>
                </div>
                
                <div id="tab-details">
                    <?php echo $this->getChildHtml('product_attributes'); ?>
                </div>
                
                <div id="tab-tags">
                    <?php echo $this->getChildHtml('product_additional_data') ?>
                </div>
                
                <?php if ( $this->getChildHtml('snippet_product_view_tab_1') ): ?>
                    <div id="tab-custom-1">
                        <div class="snippet snippet-product-view-tab-1"><?php echo $this->getChildHtml('snippet_product_view_tab_1') ?></div>
                    </div>
                <?php endif; ?>
                
                <?php if ( $this->getChildHtml('snippet_product_view_tab_2') ): ?>
                    <div id="tab-custom-2">
                        <div class="snippet snippet-product-view-tab-2"><?php echo $this->getChildHtml('snippet_product_view_tab_2') ?></div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        
        <ul class="social-widgets cf">
            <li class="soc-tw">
                <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </li>
            
            <li class="soc-fb">
                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
                
                <div class="fb-like" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
            </li>
            
            <li class="soc-gp">
                <!-- Place this tag where you want the +1 button to render -->
                <div class="g-plusone" data-size="medium"></div>
                
                <!-- Place this render call where appropriate -->
                <script type="text/javascript">
                  (function() {
                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                    po.src = 'https://apis.google.com/js/plusone.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                  })();
                </script>
            </li>
                
            <li class="soc-pi">
                <script type="text/javascript">
                (function() {
                    window.PinIt = window.PinIt || { loaded:false };
                    if (window.PinIt.loaded) return;
                    window.PinIt.loaded = true;
                    function async_load(){
                        var s = document.createElement("script");
                        s.type = "text/javascript";
                        s.async = true;
                        s.src = "http://assets.pinterest.com/js/pinit.js";
                        var x = document.getElementsByTagName("script")[0];
                        x.parentNode.insertBefore(s, x);
                    }
                    if (window.attachEvent)
                        window.attachEvent("onload", async_load);
                    else
                        window.addEventListener("load", async_load, false);
                })();
                </script>
                
                <!-- Customize and include for EACH button in the page -->
                <a href=<?php echo "http://pinterest.com/pin/create/button/?url=".$this->helper('core/url')->getCurrentUrl()."&media=".$_product->getImageUrl()."&description=".urlencode($_product->getName()." $".number_format($_product->getPrice(),2)) ?> class="pin-it-button" count-layout="horizontal">Pin It</a>
            </li>
        </ul>
    </div>
    
    <div class="grid_5 pull_7">
        <div class="product-media">
            <?php echo $this->getChildHtml('media') ?>
        </div>
        
        <?php echo $this->getChildHtml('related_products') ?>
    </div>
</div>

<?php echo $this->getChildHtml('upsell_products') ?>

<div class="grid">
    <div class="grid_5">
        <?php echo $this->getChildHtml('product_review_form') ?>
    </div>
    
    <div class="grid_7">
        <?php echo $this->getChildHtml('product_reviews') ?>
    </div>
</div>

<?php if ( $this->getChildHtml('snippet_product_view_bottom') ): ?>
    <div class="snippet snippet-product-view-bottom"><?php echo $this->getChildHtml('snippet_product_view_bottom') ?></div>
<?php endif; ?>
