<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2014 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.6
*/
?>

<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>

<li class="item">
	<a class="product-name" href="<?php echo $this->getProductUrl() ?>"><?php echo $this->getProductName() ?></a>
	
	<a class="product-image" href="<?php echo $this->getProductUrl()?>"><img src="<?php echo $this->getProductThumbnail()->resize(50)->setWatermarkSize('30x10'); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
	
	<?php /* GravDept, hide redundant link to product view */ ?>
	<?php /*
	<?php if ($isVisibleProduct): ?>
    	<a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item') ?>" class="btn-edit"><?php echo $this->__('Edit item')?></a>
    <?php endif ?>
	*/ ?>
	
	<?php if ($canApplyMsrp): ?>
		<span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>
	<?php else: ?>
		<dl>
			<dt><abbr title="<?php echo $this->__('Quantity') ?>"><?php echo $this->__('Qty') ?></abbr>:</dt>
			<dd><?php echo $this->getQty() ?></dd>
			
			<dt class="mini-cart-price-label"><?php echo $this->__('Price') ?>:</dt>
			<dd>
				<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
						<?php echo $this->__('Excl. Tax'); ?>:
					<?php endif; ?>
					
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
					<?php endif; ?>
					
					<?php if (Mage::helper('weee')->getApplied($_item)): ?>
						
						<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						<?php endif; ?>
						
						<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
							<span><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
						<?php endif; ?>
					<?php endif; ?>
				<?php endif; ?>
		
				<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
					
					<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
						<br /><?php echo $this->__('Incl. Tax'); ?>:
					<?php endif; ?>
					
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
					<?php endif; ?>
					
					<?php if (Mage::helper('weee')->getApplied($_item)): ?>
						<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						<?php endif; ?>
						
						<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
							<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
						<?php endif; ?>
					<?php endif; ?>
				<?php endif; ?>
			</dd>
		</dl>
	<?php endif; /*Can apply MSRP*/ ?>
	
	<?php if ($_options = $this->getOptionList()):?>
		<p class="has-options"><?php echo $this->__('Options shown in cart.') ?></p>
		<?php
		// GravDept:
		// Hide options in mini-cart.
		?>
		<?php /*
		<dl>
			<?php foreach ($_options as $_option) : ?>
				<dt><?php echo $this->escapeHtml($_option['label']) ?>:</dt>
				<dd>
					<?php if (is_array($_option['value'])): ?>
						<?php echo nl2br(implode("\n", $_option['value'])) ?>
					<?php else: ?>
						<?php echo $_option['value'] ?>
					<?php endif; ?>
				</dd>
			<?php endforeach; ?>
		</dl>
		*/ ?>
	<?php endif; ?>
	
	<a class="btn-remove" href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove item') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>');"><?php echo $this->__('Remove item') ?></a>
</li>
