<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<?php $_wishlistItem = $this->getWishlistItem(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getUpdateUrl($_wishlistItem); ?>

<div class="update-wishlist-config">
    <?php if ($this->helper('wishlist')->isAllow()) : ?>
        <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-compare button"><?php echo $this->__('Update Wishlist') ?></a>
    <?php endif; ?>
    
    <?php /*
    <ul class="add-to-links">
        <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-compare"><?php echo $this->__('Update Wishlist') ?></a></li>
        <?php endif; ?>
        
        <?php $_product = $this->getProduct(); ?>
        <?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
        
        <?php if ($_compareUrl) : ?>
            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
        <?php endif; ?>
    </ul>
    */ ?>
</div>