<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<div id="logged-out" class="grid-block">
	<h1><?php echo $this->__('Signed Out') ?></h1>
	<p><?php echo $this->__('You are signed out of your account.') ?></p>
	<p><a class="button" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Sign In') ?></a></p>
</div>
