<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<button type="submit" class="button btn-checkout button-large" onclick="review.save();"><?php echo $this->__('Place Order') ?></button>
