<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2014 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.6
*/
?>

<?php $_item = $this->getItem()?>

<tr>
	<td>
		<a class="product-name" href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
		
		<?php if ($_options = $this->getOptionList()):?>
			<dl class="item-options">
				<?php foreach ($_options as $_option) : ?>
					<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
					
					<dt><?php echo $this->escapeHtml($_option['label']) ?>:</dt>
					
					<dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
						<?php if (isset($_formatedOptionValue['full_view'])): ?>
							<div class="truncated_full_value">
								<dl class="item-options">
									<dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
									<dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
								</dl>
							</div>
						<?php endif; ?>
					</dd>
				<?php endforeach; ?>
			</dl>
		<?php endif;?>
		<?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
			<?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
		<?php endif; ?>
	</td>
	
	<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<td class="a-right">
			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<div class="cart-price">
			<?php endif; ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
					<?php endif; ?>
				</div>
	
			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php endif; ?>
				</div>
	
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
						<span class="nobr">
							<?php echo Mage::helper('weee')->__('Total'); ?>:<br />
							<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
						</span>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</td>
	<?php endif; ?>
	
	<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<td class="a-right">
			<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
			
			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<div class="cart-price">
			<?php endif; ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
					<?php endif; ?>
				</div>
			
			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php endif; ?>
				</div>
	
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
						<span class="nobr">
							<?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:
							<br />
							<?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
						</span>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</td>
	<?php endif; ?>
	
	<td class="a-right">
		<?php echo $_item->getQty() ?>
	</td>
	
	<!-- sub total starts here -->
	<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<td class="a-right">
			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<div class="cart-price">
			<?php endif; ?>
	
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
					<?php endif; ?>
			</div>
			
			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php endif; ?>
				</div>
	
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
						<span class="nobr">
							<?php echo Mage::helper('weee')->__('Total'); ?>:<br />
							<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
						</span>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</td>
	<?php endif; ?>
	
	<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<td class="a-right">
			<?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<div class="cart-price">
			<?php endif; ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
					<?php endif; ?>
				</div>
	
			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
					<?php endif; ?>
				</div>
	
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
						<span class="nobr">
							<?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br />
							<?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
						</span>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</td>
	<?php endif; ?>
	
</tr>
