<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<p><?php echo $this->__('Ship to more than one destination:') ?></p>
<a class="button button-small button-subtle" href="<?php echo $this->getCheckoutUrl()?>"><?php echo $this->__('Multi-Address Checkout') ?></a>
