<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2014 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.7
 */
?>

<?php /** @var $this Mage_Checkout_Block_Multishipping_Overview */ ?>

<div class="page-title">
    <h1><?php echo $this->__('Review Order'); ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>

<form id="review-order-form" class="multiship-review-form" action="<?php echo $this->getPostActionUrl(); ?>" method="post" onsubmit="return showLoader();">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <div id="multiship-review-billing-info" class="block">
        <div class="block-title">
            <h2><?php echo $this->__('Billing Information'); ?></h2>
        </div>
        
        <div class="block-content lined">
            <div class="grid">
                <div class="grid_3 alpha">
                    <?php $_address=$this->getBillingAddress(); ?>
                    <h3>
                        <?php echo $this->__('Billing Address'); ?>
                        <a href="<?php echo $this->getEditBillingAddressUrl($_address); ?>"><?php echo $this->__('Edit'); ?></a>
                    </h3>
                    <address><?php echo $_address->format('html'); ?></address>
                </div>
    
                <div class="grid_3 omega">
                    <h3>
                        <?php echo $this->__('Payment Method'); ?>
                        <a href="<?php echo $this->getEditBillingUrl(); ?>"><?php echo $this->__('Edit'); ?></a>
                    </h3>
                    
                    <input type="hidden" name="payment[cc_number]" value="<?php echo $this->escapeHtml($this->getPayment()->getCcNumber())?>" />
                    <input type="hidden" name="payment[cc_cid]" value="<?php echo $this->escapeHtml($this->getPayment()->getCcCid())?>" />
                    <div class="payment-method"><?php echo $this->getPaymentHtml(); ?></div>
                </div>
            </div>
        </div>
     </div>
     
    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    
    <div class="block">
        <div class="block-title">
            <h2><?php echo $this->__('Shipping Information'); ?></h2>
        </div>
        
        <div class="block-content">
            <ul id="multiship-review-shipping-list">
                <?php foreach ($this->getShippingAddresses() as $_index => $_address): ?>
                    <li>
                        <h3><?php echo $this->__('Address %s of %s', ($_index+1), $this->getShippingAddressCount()); ?></h3>
                        
                        <div class="grid">
                            <div class="grid_3 alpha">
                                <div class="liner-left">
                                    <h4>
                                        <?php echo $this->__('Destination'); ?>
                                        <a href="<?php echo $this->getEditShippingAddressUrl($_address); ?>"><?php echo $this->__('Edit'); ?></a>
                                    </h4>
                                    
                                    <address><?php echo $_address->format('html'); ?></address>
                                </div>
                            </div>
                            
                            <div class="grid_3">
                                <h4>
                                    <?php echo $this->__('Shipping Method'); ?>
                                    <a href="<?php echo $this->getEditShippingUrl(); ?>"><?php echo $this->__('Edit'); ?></a>
                                </h4>
                                
                                <?php if($_rate=$this->getShippingAddressRate($_address)): ?>
                                    <p class="shipping-method">
                                        <?php echo $this->escapeHtml($_rate->getCarrierTitle()); ?> - <?php echo $this->escapeHtml($_rate->getMethodTitle()); ?>
                                        <?php $_excl = $this->getShippingPriceExclTax($_address); ?>
                                        <?php $_incl = $this->getShippingPriceInclTax($_address); ?>
                                        <?php echo $_excl; ?>
                                        
                                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                        <?php endif; ?>
                                    </p>
                                <?php endif; ?>
                            </div>
                            
                            <div class="grid_6 omega">
                                <h4>
                                    <?php echo $this->__('Items'); ?>
                                    <a href="<?php echo $this->getAddressesEditUrl(); ?>"><?php echo $this->__('Edit'); ?></a>
                                </h4>
                                
                                <table class="data-table multiship-review-table" id="overview-table-<?php echo $_address->getId(); ?>">
                                    <thead>
                                        <tr>
                                            <th rowspan="<?php echo $mergedCells; ?>" class="width-full"><?php echo $this->__('Product'); ?></th>
                                            <th colspan="<?php echo $mergedCells; ?>" class="a-right"><?php echo $this->__('Price'); ?></th>
                                            <th rowspan="<?php echo $mergedCells; ?>" class="a-right"><abbr title="<?php echo $this->__('Quantity'); ?>"><?php echo $this->__('Qty.'); ?></abbr></th>
                                            <th colspan="<?php echo $mergedCells; ?>" class="a-right"><?php echo $this->__('Subtotal'); ?></th>
                                        </tr>
                                        
                                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                            <tr>
                                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false); ?></th>
                                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true); ?></th>
                                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false); ?></th>
                                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true); ?></th>
                                            </tr>
                                        <?php endif; ?>
                                    </thead>
                                    
                                    <tfoot>
                                        <?php echo $this->renderTotals($this->getShippingAddressTotals($_address)); ?>
                                    </tfoot>
                                    
                                    <tbody>
                                        <?php foreach ($this->getShippingAddressItems($_address) as $_item): ?>
                                            <?php echo $this->getRowItemHtml($_item); ?>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    
    <?php if ($this->getQuote()->hasVirtualItems()): ?>
        <div class="block">
            <div class="block-title">
                <h2><?php echo $this->__('Other items in your order'); ?></h2>
                <a class="button" href="<?php echo $this->getVirtualProductEditUrl(); ?>"><?php echo $this->__('Edit'); ?></a>
            </div>
            
            <div class="block-content lined">
                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                
                <table id="virtual-overview-table" class="data-table multiship-review-table">
                    <thead>
                        <tr>
                            <th rowspan="<?php echo $mergedCells; ?>" class="width-full"><?php echo $this->__('Product'); ?></th>
                            <th colspan="<?php echo $mergedCells; ?>" class="a-right"><?php echo $this->__('Price'); ?></th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-right"><abbr title="<?php echo $this->__('Quantity'); ?>"><?php echo $this->__('Qty.'); ?></abbr></th>
                            <th colspan="<?php echo $mergedCells; ?>" class="a-right"><?php echo $this->__('Subtotal'); ?></th>
                        </tr>
                        
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <tr>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false); ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true); ?></th>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false); ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true); ?></th>
                            </tr>
                        <?php endif; ?>
                    </thead>
                    
                    <tfoot>
                        <?php echo $this->renderTotals($this->getBillinAddressTotals()); ?>
                    </tfoot>
                    
                    <tbody>
                        <?php foreach ($this->getVirtualItems() as $_item): ?>
                            <?php echo $this->getRowItemHtml($_item); ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif; ?>

    <?php echo $this->getChildHtml('items_after'); ?>

    <?php echo $this->getChildHtml('agreements'); ?>

    <div id="checkout-review-submit" class="buttons-set multiship-actions">
        <a class="button button-subtle" href="<?php echo $this->getBackUrl(); ?>"><?php echo $this->__('Go Back'); ?></a>
        
        <div class="grand-total">
            <?php echo $this->__('Grand Total:'); ?>
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()); ?>
        </div>
        
        <button type="submit" class="button button-large" id="review-button"><?php echo $this->__('Place Order'); ?></button>
        
        <span id="review-please-wait" class="please-wait" style="display:none;"><?php echo $this->__('Sending your order...'); ?></span>
    </div>
</form>
    
<script>
    var submitted = false;

    function showLoader()
    {
        if (submitted) {
            return false;
        }
        if ($('checkout-agreements')) {
            var checkboxes = $$('#checkout-agreements input');
            for (var i=0, l=checkboxes.length; i<l; i++) {
                if (!checkboxes[i].checked) {
                    alert("<?php echo $this->__('Please agree to all terms and conditions before placing the orders.')?>");
                    return false;
                }
            }
        }

        submitted = true;
        var step='review';
        Element.show(step+'-please-wait');
        
        // GravDept:
        // Remove this.
        /*
        $(step+'-buttons-container').setStyle({opacity:.5});
        $(step+'-buttons-container').descendants().each(function(s) {
              s.disabled = true;
        });
        */
        return true;
    }
</script>
