<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2014 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.7
 */
?>

<div class="page-title">
	<h1 data-role="page-title"><?php echo $this->__('Order Success'); ?></h1>
</div>

<p><?php echo $this->__('Thanks for your purchase! We sent you an order summary email and when your order ships we\'ll forward the tracking number.'); ?></p>

<?php if($_orderIds = $this->getOrderIds()): ?>
	<h2><?php echo $this->__('Your Order Number(s):'); ?></h2>
	
	<?php $flag = false ?>
	<p data-role="order-numbers">
		<?php foreach ($_orderIds as $orderId=>$incrementId): ?>
			<?php if ($flag): ?>
				<?php echo '<br />' ?>
			<?php endif; ?>
			
			<?php $flag = true ?>
			<a href="<?php echo $this->getViewOrderUrl($orderId); ?>"><?php echo $incrementId; ?></a>
		<?php endforeach; ?>
	</p>
<?php endif; ?>

<?php echo $this->getChildHtml(); ?>

<a class="button" href="<?php echo $this->getContinueUrl(); ?>"><?php echo $this->__('Continue Shopping'); ?></a>
