<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<ul class="payment-icons-list">
	<li class="visa" title="<?php echo $this->__('Visa') ?>"><?php echo $this->__('Visa') ?></li>
	<li class="mastercard" title="<?php echo $this->__('MasterCard') ?>"><?php echo $this->__('MasterCard') ?></li>
	<li class="amex" title="<?php echo $this->__('American Express') ?>"><?php echo $this->__('American Express') ?></li>
	<li class="discover" title="<?php echo $this->__('Discover') ?>"><?php echo $this->__('Discover') ?></li>
	<li class="paypal" title="<?php echo $this->__('PayPal') ?>"><?php echo $this->__('PayPal') ?></li>
</ul>
