<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<?php
/* GravDept. Used in "My Reviews" & "Product View".
 *
 * Replaced URLs with custom string to anchor #review-form
 * Original code: <a href="<?php echo $this->getReviewsUrl() ?>">
 */
?>

<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif; ?>
        
        <p class="rating-links">
	        <?php /* GravDept, custom URLs */ ?>
            <?php if ( $this->getReviewsCount()==1 ): ?>
            	<a href="<?php echo $this->getUrl('') . $this['product']['url_key'] ?>/#review-form"><?php echo $this->__('%d review', $this->getReviewsCount()) ?></a>
            <?php else: ?>
            	<a href="<?php echo $this->getUrl('') . $this['product']['url_key'] ?>/#review-form"><?php echo $this->__('%d reviews', $this->getReviewsCount()) ?></a>
            <?php endif; ?>
            
            <?php /* GravDept, hide this, requires standalone review page */ ?>
            <?php /*<a class="add-your-review" href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Add Your Review') ?></a>*/ ?>
        </p>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <?php /* GravDept, hide this, requires standalone review page */ ?>
    <?php /*<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Write A Review') ?></a></p>*/ ?>
    <p class="no-rating"><a class="button button-small button-subtle" href="<?php echo $this->getUrl('') . $this['product']['url_key'] ?>/#review-form"><?php echo $this->__('Write A Review') ?></a></p>
<?php endif; ?>
