<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<h1><?php echo $this->__('Your Tags') ?></h1>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->getTags()): ?>
	<ul class="tags-list">
		<?php foreach ($this->getTags() as $_tag): ?>
			<li><a href="<?php echo $this->getUrl('tag/customer/view', array('tagId' => $_tag->getTagId())) ?>" <?php /* style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;" */ ?>><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
		<?php endforeach; ?>
	</ul>
<?php else: ?>
	<p><?php echo $this->__('You have not tagged any products yet.') ?></p>
<?php endif; ?>
