<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<div class="grid-block">
	<h1><?php echo $this->__('Forgot Password') ?></h1>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="grid">	
	<div class="grid_6">
		<p><?php echo $this->__('Please enter your email address below. We will send you a link to reset your password.') ?></p>

		<form id="forgot-password-form" class="stack-form" action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post">
			<ul class="form-list">
				<li>
					<label for="email_address" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
					
					<div class="input-box">
    					<input type="email" id="email_address" name="email" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
    				</div>
				</li>
				
				<?php echo $this->getChildHtml('form.additional.info'); ?>
			</ul>
	        
	        <div class="buttons-set">
    			<button type="submit" class="button"><?php echo $this->__('Reset Password') ?></button>
    		</div>
		</form>
		
		<script type="text/javascript">
			//<![CDATA[
				var dataForm = new VarienForm('forgot-password-form', true);
			//]]>
		</script>
	</div>
</div>
