<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<div class="grid-block">
	<h1><?php echo $this->__('Reset Your Password'); ?></h1>
	
	<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
	
	<form id="reset-password-form" class="stack-form" action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post">
		<ul class="form-list">
			<li>
				<label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
				
				<div class="input-box">
    				<input type="password" class="input-text required-entry validate-password" name="password" id="password" title="<?php echo $this->__('New Password') ?>" />
    			</div>
			</li>
			
			<li>
				<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
				
				<div class="input-box">
				    <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" title="<?php echo $this->__('Confirm New Password') ?>" />
				</div>
			</li>
		</ul>
	    
	    <div class="buttons-set">
    		<button type="submit" class="button"><?php echo $this->__('Reset Password'); ?></button>
    	</div>
	</form>
	
	<script type="text/javascript">
	/*<![CDATA[*/
		var dataForm = new VarienForm('reset-password-form', true);
	/*]]>*/
	</script>
</div>
