<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<dl id="checkout-payment-method-load" class="billing-methods">
   <?php
   // Magento:
   // Content dynamically loaded.
   // Content from the methods.phtml is loaded during the ajax call.
   ?>
</dl>
