<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php
// GravDept:
// This page is does not exist in "base/default" package.
// Modified to place category title block above sidebar filter and product list.
// Derived functionality from: /template/catalog/category/view.phtml
?>

<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<?php
$_helper   = $this->helper('catalog/output');
$_category = $this->getCurrentCategory();
$_imgHtml  = '';

if ($_imgUrl = $_category->getImageUrl()) {
	$_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" />';
	$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>

<?php
// GravDept:
// Show only (image) or (H1 + description).
?>

<div id="category-landing" class="grid-block">
	<?php if ($_imgUrl): ?>
		<h1 class="category-image"><?php echo $_imgHtml ?></h1>
	<?php else: ?>
		<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
		
		<?php if ($_description=$this->getCurrentCategory()->getDescription()): ?>
			<p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
		<?php endif; ?>
	<?php endif; ?>
	
	<?php /*if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
		<a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('RSS Feed') ?></a>
	<?php endif;*/ ?>
</div>
