<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<a class="product-name" href="<?php echo $this->getProductUrl(); ?>">
	<?php echo $this->escapeHtml($this->getProductName()); ?>
</a>

<?php if ($_options = $this->getOptionList()):?>
	<dl class="item-options">
		<?php foreach ($_options as $_option): ?>
			<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option); ?>
			
			<dt><?php echo $this->escapeHtml($_option['label']); ?></dt>
			
			<dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
				<?php echo $_formatedOptionValue['value']; ?>
				
				<?php if (isset($_formatedOptionValue['full_view'])): ?>
					<div class="truncated_full_value">
						<dl class="item-options">
							<dt><?php echo $this->escapeHtml($_option['label']); ?>:</dt>
							<dd><?php echo $_formatedOptionValue['full_view']; ?></dd>
						</dl>
					</div>
				<?php endif; ?>
			</dd>
		<?php endforeach; ?>
	</dl>
<?php endif; ?>
