<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.1
 */
?>

<!DOCTYPE html>
<?php echo $this->getChildHtml('gravdept_html') ?>

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body class="page-empty <?php echo $this->getBodyClass() ? $this->getBodyClass() : ''; ?>">

	<?php echo $this->getChildHtml('after_body_start') ?>
	<?php echo $this->getChildHtml('content') ?>
	<?php echo $this->getChildHtml('before_body_end') ?>
	<?php echo $this->getAbsoluteFooter() ?>
	
</body>
</html>
