<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<div class="grid-block">
	<h1><?php echo $this->__('Redirecting...') ?></h1>

	<?php if($this->getMessage()): ?>
		<p><?php echo $this->getMessage() ?></p>
	<?php endif; ?>
	
	<?php echo $this->getRedirectOutput() ?>
	
	<?php if(!$this->isHtmlFormRedirect()): ?>
		<p><?php echo $this->__('Click <a href="%s">here</a> if nothing has happened', $this->getTargetURL()) ?></p>
	<?php endif; ?>
</div>
