<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.1
 */
?>

<form id="newsletter-form" action="<?php echo $this->getUrl('newsletter/subscriber/new') ?>" method="post">
	<label for="newsletter-email"><?php echo $this->__('Subscribe to our Newsletter') ?></label>
	<input type="text" id="newsletter-email" name="email" class="required-entry validate-email" placeholder="<?php echo $this->__('name@example.com') ?>" />
	<button type="submit"><?php echo $this->__('Subscribe') ?></button>
</form>

<script type="text/javascript">
	//<![CDATA[
	var newsletterSubscriberFormDetail = new VarienForm('newsletter-form');
	//]]>
</script>
