<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php
/**
 * Category left navigation
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>

<?php if (!Mage::registry('current_category')) return ?>

<?php $_categories = $this->getCurrentChildCategories(); ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>

<?php if ($_count): ?>
    <div class="block block-layered-nav">
        <div class="block-title">
            <h2><?php echo $this->__('Shop By'); ?></h2>
        </div>
        
        <div class="block-content filter">
            <dl id="narrow-by-list">
                <dt><?php echo $this->__('Category'); ?></dt>
                <dd>
                    <ol>
                        <?php foreach ($_categories as $_category): ?>
                            <?php if ($_category->getIsActive()): ?>
                                <li>
                                    <a href="<?php echo $this->getCategoryUrl($_category); ?>" <?php if ($this->isCategoryActive($_category)): ?>class="current"<?php endif; ?>>
                                        <span class="count"><?php echo $_category->getProductCount(); ?></span>
                                        <?php echo $this->escapeHtml($_category->getName()); ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif; ?>
