<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<div class="grid-block">
	<h1><?php echo $this->__('My Cart') ?></h1>
	
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<div class="cart-no-items">
	    <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
	    
	    <h2><?php echo $this->__('Your cart is empty.') ?></h2>
		<p><?php echo $this->__('Try a search, browse the categories, or go to the') ?> <a href="<?php echo $this->getContinueShoppingUrl(); ?>"><?php echo $this->__('home page') ?></a>.</p>
		
		<?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
	</div>
</div>

<?php if ( $this->getChildHtml('snippet_cart_empty_bottom') ): ?>
    <div class="snippet snippet-cart-empty-bottom"><?php echo $this->getChildHtml('snippet_cart_empty_bottom') ?></div>
<?php endif; ?>
