<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php /** @var $this Mage_Checkout_Block_Cart_Shipping */ ?>

<div id="cart-shipping-box" class="block">
    <div class="block-title">
    	<h2><?php echo $this->__('Estimate Shipping &amp; Tax') ?></h2>
    	<p><?php echo $this->__('Enter your shipping destination to get an estimate.') ?></p>
    </div>
    
    <div class="block-content">
        <div class="grid">
        	<div class="grid_4 alpha">
        		<form id="shipping-zip-form" class="stack-form" action="<?php echo $this->getUrl('checkout/cart/estimatePost') ?>" method="post">
        			<h3><?php echo $this->__('Destination') ?></h3>
        			
        			<ul class="form-list">
        				<li>
        					<label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
        					
        					<div class="input-box">
        						<?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
        					</div>
        				</li>
        				
        				<?php /* Magento. Disabled since Mage 1.4.0.1 base/default */ ?>
        				<?php /*if($this->getStateActive()):*/ ?>
        					<li>
        						<label for="region_id"<?php if ($this->isStateProvinceRequired()) echo ' class="required"' ?>><?php if ($this->isStateProvinceRequired()) echo '<em>*</em>' ?><?php echo $this->__('State/Province') ?></label>
        						
        						<div class="input-box">
            						<select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : '') ?>>
            							<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            						</select>
            						
            						<script type="text/javascript">
            						   //<![CDATA[
            							   $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
            						   //]]>
            						</script>
            						
            						<input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getEstimateRegion()) ?>" style="display:none;" />
        						</div>
        					</li>
        				<?php /*endif;*/ ?>
        				
        				<?php if($this->getCityActive()): ?>
        					<li>
        						<label for="city"<?php if ($this->isCityRequired()) echo ' class="required"' ?>><?php if ($this->isCityRequired()) echo '<em>*</em>' ?><?php echo $this->__('City') ?></label>
        						
        						<div class="input-box">
        						    <input class="input-box <?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->escapeHtml($this->getEstimateCity()) ?>" />
        						</div>
        					</li>
        				<?php endif; ?>
        				
        				<li>
        					<label for="postcode"<?php if ($this->isZipCodeRequired()) echo ' class="required"' ?>><?php if ($this->isZipCodeRequired()) echo '<em>*</em>' ?><?php echo $this->__('Zip/Postal Code') ?></label>
        					
        					<div class="input-box">
            					<input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->escapeHtml($this->getEstimatePostcode()) ?>" />
            				</div>
        				</li>
        			</ul>
        			
        			<div class="buttons-set">
            			<button type="button" class="button" onclick="coShippingMethodForm.submit()"><?php echo $this->__('Get Estimate') ?></button>
            		</div>
        		</form>
        		
        		<script type="text/javascript">
        			//<![CDATA[
        				new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
        			//]]>
        		</script>
        	</div>
        
        	<?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
        		<div class="grid_4 omega">
        			<form id="co-shipping-method-form" class="stack-form" action="<?php echo $this->getUrl('checkout/cart/estimateUpdatePost') ?>">
        				<h3><?php echo $this->__('Method / Type') ?></h3>
        				
        				<dl class="sp-methods">
        					<?php foreach ($_shippingRateGroups as $code => $_rates): ?>
        						<dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
        						<dd>
        							<ul>
        							<?php foreach ($_rates as $_rate): ?>
        								<li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"'; ?>>
        								   <?php if ($_rate->getErrorMessage()): ?>
        										<?php echo $_rate->getErrorMessage() ?>
        								   <?php else: ?>
        										<input name="estimate_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
        										<label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
        											<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
        											<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
        											<?php echo $_excl; ?>
        											<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
        												(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
        											<?php endif; ?>
        										</label>
        								   <?php endif ?>
        								</li>
        							<?php endforeach; ?>
        							</ul>
        						</dd>
        					<?php endforeach; ?>
        				</dl>
        				
        				<div class="buttons-set">
            				<button type="submit" class="button"><?php echo $this->__('Update Order Total') ?></button>
            			</div>
        			</form>
        		</div>
        	<?php endif; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
	//<![CDATA[
		var coShippingMethodForm = new VarienForm('shipping-zip-form');
		var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

		coShippingMethodForm.submit = function () {
			var country = $F('country');
			var optionalZip = false;

			for (i=0; i < countriesWithOptionalZip.length; i++) {
				if (countriesWithOptionalZip[i] == country) {
					optionalZip = true;
				}
			}
			if (optionalZip) {
				$('postcode').removeClassName('required-entry');
			}
			else {
				$('postcode').addClassName('required-entry');
			}
			return VarienForm.prototype.submit.bind(coShippingMethodForm)();
		}
	//]]>
</script>
