<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>

<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>
<?php else: ?>
    <div class="block">
        <div class="block-title">
            <h2><?php echo $this->__('Order Total') ?></h2>
        </div>
        
        <div class="block-content">
            <table id="shopping-cart-totals-table" class="flex-table">
                <tfoot>
                    <?php echo $this->renderTotals('footer'); ?>
                </tfoot>
                <tbody>
                    <?php echo $this->renderTotals(); ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>
