<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php if ($crumbs && is_array($crumbs)): ?>
	<ul class="breadcrumbs">
		<?php foreach ($crumbs as $_crumbName=>$_crumbInfo): ?>
			<li class="<?php echo $_crumbName; ?>">
				<?php if ($_crumbInfo['link']): ?>
					<a href="<?php echo $_crumbInfo['link'] ?>"><?php echo $this->escapeHtml($_crumbInfo['label']); ?></a>
				<?php elseif ($_crumbInfo['last']): ?>
					<?php echo $this->escapeHtml($_crumbInfo['label']); ?>
				<?php else: ?>
					<?php echo $this->escapeHtml($_crumbInfo['label']); ?>
				<?php endif; ?>
				
				<?php if (!$_crumbInfo['last']): ?>
					<span>/</span>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
