<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<?php /* Magento: original */ ?>
<?php /*<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />*/ ?>

<?php /* GravDept: simpler charset */ ?>
<meta charset="utf-8">

<title><?php
// see: http://www.magentocommerce.com/boards/viewthread/69268/
// see: http://inchoo.net/ecommerce/magento/change-any-page-title-in-magento/
	
if (Mage::getSingleton('cms/page')->getTitle()=="Home") { echo $this->getDefaultTitle(); }
elseif ($this->getForcedTitle()) { echo Mage::getStoreConfig('design/head/title_prefix').' '.$this->getForcedTitle().' '.Mage::getStoreConfig('design/head/title_suffix'); }
elseif ($this->getHeaderTitle()) { echo Mage::getStoreConfig('design/head/title_prefix').' '.$this->getHeaderTitle().' '.Mage::getStoreConfig('design/head/title_suffix'); }
else { echo $this->getTitle(); }
?></title>

<!-- Meta -->
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />

<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<!-- CSS + JS -->
<?php echo $this->getCssJsHtml() ?>

<?php /*   // Magento trash
<script type="text/javascript">
	//<![CDATA[
	var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
	var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
	//]]>
</script>
*/ ?>

<!-- other -->
<?php echo $this->getChildHtml() ?>

<?php /* GravDept note: required for inline translation. See: "MageAdmin > Config > Advanced > Developer" and "page.xml" */ ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>


<?php echo $this->getIncludes() ?>
