<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.4
 */
?>
<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>

<?php /* this pager is used only in account dashboard -- not in the catalog */ ?>

<?php if($this->getCollection()->getSize()): ?>

	<?php if($this->getUseContainer()): ?>
		<div class="pager">
	<?php endif ?>
		
		<!-- item count -->
		<?php if($this->getShowAmounts()): ?>
			<p class="amount">
				<?php if($this->getLastPageNum()>1): ?>
				    <?php echo $this->__('%s-%s <span>of</span> %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
				<?php elseif( $this->getLastPageNum()==1 && $this->getTotalNum()==1 ): ?>
					<?php echo $this->__('%s total', $this->getTotalNum()) ?> 
				<?php else: ?>
				    <?php echo $this->__('%s total', $this->getTotalNum()) ?>
				<?php endif; ?>
			</p>
		<?php endif ?>
		
		<!-- show per page -->
		<?php if($this->getShowPerPage()): ?>
			<div class="limiter">
				<label for="pager-show"><?php echo $this->__('Show') ?></label>
				<select id="pager-show" onchange="setLocation(this.value)">
				<?php foreach ($this->getAvailableLimit() as $_key=>$_limit): ?>
					<option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
						<?php echo $_limit ?>
						<?php if ( is_numeric($_limit) ) { echo $this->__(' per page'); } ?>
						<?php if ( ! is_numeric($_limit) ) { echo $this->__(' items'); } ?>
					</option>
				<?php endforeach; ?>
				</select>
			</div>
		<?php endif ?>
		
		<!-- pagination -->
		<?php if($this->getLastPageNum()>1): ?>
			<ol class="pages">
				<?php if ($this->canShowPreviousJump()): ?>
					<li><a class="previous-jump" title="Previous Jump" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
				<?php endif; ?>
				
				<?php if (!$this->isFirstPage()): ?>
					<li>
						<a class="previous <?php if(!$this->getAnchorTextForPrevious()): ?>i-previous<?php endif;?>" title="Previous Page" href="<?php echo $this->getPreviousPageUrl() ?>">
							<?php if(!$this->getAnchorTextForPrevious()): ?>
								<?php echo $this->__('Previous') ?>
							<?php else: ?>
								<?php echo $this->getAnchorTextForPrevious() ?>
							<?php endif;?>
						</a>
					</li>
				<?php endif;?>
				
				<?php if ($this->canShowFirst()): ?>
					<li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
				<?php endif;?>
		
				<?php foreach ($this->getFramePages() as $_page): ?>
					<?php if ($this->isPageCurrent($_page)): ?>
						<li><span class="current"><?php echo $_page ?></span></li>
					<?php else: ?>
						<li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
					<?php endif;?>
				<?php endforeach;?>
		
				<?php if ($this->canShowLast()): ?>
				  <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a><li>
				<?php endif;?>
		
				<?php if (!$this->isLastPage()): ?>
					<li>
						<a class="next <?php if(!$this->getAnchorTextForNext()): ?>i-next<?php endif; ?>" title="Next Page" href="<?php echo $this->getNextPageUrl() ?>">
							<?php if(!$this->getAnchorTextForNext()): ?>
								<?php echo $this->__('Next') ?>
							<?php else: ?>
								<?php echo $this->getAnchorTextForNext() ?>
							<?php endif;?>
						</a>
					</li>
				<?php endif;?>
				
				<?php if ($this->canShowNextJump()): ?>
					<li><a class="next-jump" title="Next Jump" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
				<?php endif;?>
			</ol>
		<?php endif; ?>

	<?php if($this->getUseContainer()): ?>
		</div>
	<?php endif ?>

<?php endif ?>
