<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top') ?>

<?php if($_menu): ?>
    <div class="nav-container">
        <ul id="nav">
            <?php /* GravDept: add snippet */ ?>
            <?php if ( $this->getChildHtml('snippet_nav_before') ): ?>
                <?php echo $this->getChildHtml('snippet_nav_before') ?>
            <?php endif; ?>
            
            <?php echo $_menu ?>
            
            <?php /* GravDept: add snippet */ ?>
            <?php if ( $this->getChildHtml('snippet_nav_after') ): ?>
                <?php echo $this->getChildHtml('snippet_nav_after') ?>
            <?php endif; ?>
        </ul>
    </div>
<?php endif ?>
