<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<h1><?php echo $this->__('Change Billing Address') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="grid">
	<div class="grid_4 alpha">
		<h2><?php echo $this->__('Create new address') ?></h2>
		<a class="button" href="<?php echo $this->getAddNewUrl() ?>"><?php echo $this->__('Add New Address') ?></a>
	</div>
	
	<div class="grid_8 omega">
	    <h2><?php echo $this->__('Select from address book') ?></h2>
	    
		<ul class="multiship-change-billing-address">
			<?php foreach ($this->getAddressCollection() as $_address): ?>
				<li>
				    <address><?php echo $_address->format('html') ?></address>
				    
				    <?php if($this->isAddressDefaultBilling($_address)): ?>
				       <p class="is-default"><?php echo $this->__('This is your default billing address.') ?></p>
				    <?php endif; ?>
				    
				    <?php if($this->isAddressDefaultShipping($_address)): ?>
				    	<p class="is-default"><?php echo $this->__('This is your default shipping address.') ?></p>
				    <?php endif; ?>
				    
					<a class="button" href="<?php echo $this->getSetAddressUrl($_address) ?>"><?php echo $this->__('Select This Address') ?></a>
					<a class="button button-small button-subtle" href="<?php echo $this->getEditAddressUrl($_address) ?>"><?php echo $this->__('Edit') ?></a>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

<div class="multiship-actions">
	<a class="button" href="<?php echo $this->getBackUrl() ?>"><?php echo $this->__('Go Back') ?></a>
</div>
