<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2014 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.7
*/
?>

<?php /** @var $this Mage_Paypal_Block_Express_Review */ ?>

<div class="grid-block">
    <div class="page-title">
        <h1><?php echo $this->__('Review Order'); ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->toHtml(); ?>

    <div class="info-set grid">
        <?php if ($this->getShippingAddress()): ?>
            <div class="grid_6 alpha">
                <div class="block">
                    <div class="block-title">
                        <h2>
                            <?php echo $this->__('Shipping Info'); ?>
                            
                            <?php if ($this->getCanEditShippingAddress()): ?>
                                &nbsp;
                                <a href="<?php echo $this->getEditUrl(); ?>"><?php echo $this->__('Edit'); ?></a>
                            <?php endif;?>
                        </h2>
                    </div>

                    <div class="block-content lined">
                        <h3><?php echo $this->__('Shipping Address'); ?></h3>

                        <address><?php echo $this->renderAddress($this->getShippingAddress()); ?></address>
                    
                        <h3><?php echo $this->__('Shipping Method'); ?></h3>

                        <form method="post" id="shipping_method_form" action="<?php echo $this->escapeHtml($this->getShippingMethodSubmitUrl()); ?>">
                            <?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()): ?>
                                <?php if ($groups = $this->getShippingRateGroups()): ?>
                                    <?php $currentRate = $this->getCurrentShippingRate(); ?>

                                    <select name="shipping_method" id="shipping_method" class="required-entry">
                                        <?php if (!$currentRate): ?>
                                            <option value=""><?php echo $this->__('Please select a shipping method...'); ?></option>
                                        <?php endif; ?>

                                        <?php foreach ($groups as $code => $rates): ?>
                                            <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)); ?>">
                                                <?php foreach ($rates as $rate):?>
                                                    <option value="<?php echo $this->renderShippingRateValue($rate); ?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ; ?>>
                                                        <?php echo $this->renderShippingRateOption($rate); ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </optgroup>
                                        <?php endforeach; ?>
                                    </select>

                                    <p class="actions">
                                        <button type="submit" class="button" id="update_shipping_method_submit">
                                            <?php echo $this->__('Update Shipping Method'); ?>
                                        </button>
                                    </p>
                                <?php else: ?>
                                    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.'); ?></p>
                                <?php endif; ?>
                            <?php else: ?>
                                <p><?php echo $this->renderShippingRateOption($this->getCurrentShippingRate()); ?></p>
                            <?php endif; ?>
                        </form>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="grid_6 omega">
            <div class="block">
                <div class="block-title">
                    <h2>
                        <?php echo $this->__('Payment Method'); ?>

                        <?php if ($this->getEditUrl()): ?>
                            &nbsp;
                            <a class="button button-small button-subtle" href="<?php echo $this->getEditUrl(); ?>"><?php echo $this->__('Edit'); ?></a>
                        <?php endif; ?>
                    </h2>
                </div>

                <div class="block-content lined">
                    <?php echo $this->escapeHtml($this->getPaymentMethodTitle()); ?>
                </div>
            </div>
        </div>
    </div>

    <?php
    // GravDept:
    // Hide heading.
    // Hierarchy is obvious.
    ?>
    <?php /*
    <h2><?php echo $this->__('Items In Your Cart'); ?></h2>
    */ ?>

    <?php
    // GravDept:
    // Hide "cart" link.
    // Kills conversion.
    ?>
    <?php /*
    <a class="button button-small button-subtle" href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Edit Cart'); ?></a>
    */ ?>

    <div id="details-reload">
        <?php echo $this->getChildHtml('details'); ?>
    </div>

    <form id="order_review_form" class="paypal-express-review-form" action="<?php echo $this->getPlaceOrderUrl(); ?>" method="post">
        <?php echo $this->getChildHtml('agreements'); ?>
        
        <div class="buttons-set buttons-set-order" id="review-buttons-container">
            <button type="button" id="review_button" class="button btn-checkout"><?php echo $this->__('Place Order'); ?></button>
            <button type="button" id="review_submit" class="button btn-checkout"><?php echo $this->__('Place Order'); ?></button>

            <span class="please-wait" id="review-please-wait" style="display:none;">
                <?php echo $this->__('Sending your order...'); ?>
            </span>
        </div>
    </form>
</div>

<script>
    // submit buttons are not needed when submitting with ajax
    $('review_submit').hide();

    if ($('update_shipping_method_submit')) {
        $('update_shipping_method_submit').hide();
    }

    <?php if ($this->getUseAjax()): ?>
        OrderReviewController.prototype._submitOrder = function() {
            if (this._canSubmitOrder) {
                if (this._pleaseWait) {
                    this._pleaseWait.show();
                }
                new Ajax.Request(this.form.action, {
                    parameters: {isAjax: 1, method: 'POST'},
                    onSuccess: function(transport) {
                        try{
                            response = eval('(' + transport.responseText + ')');
                        } catch (e) {
                            response = {};
                        }
                        if (response.redirect) {
                            setLocation(response.redirect);
                            return;
                        }
                        if (response.success) {
                            setLocation('<?php echo $this->getSuccessUrl()?>');
                            return;
                        } else {
                            var msg = response.error_messages;
                            if (typeof(msg)=='object') {
                                msg = msg.join("\n");
                            }
                            if (msg) {
                                $('review-please-wait').hide();
                                alert(msg);
                                return;
                            }
                        }
                        $('review-please-wait').hide();
                        alert('<?php echo $this->jsQuoteEscape($this->__('Unknown Error. Please try again later.')); ?>');
                        return;
                    },
                    onFailure: function(){
                        alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')); ?>');
                        $('review-please-wait').hide();
                    }
                });
            }
        }
    <?php endif; ?>

    PayPalExpressAjax = new OrderReviewController($('order_review_form'), $('review_button'),
        $('shipping_method'), $('shipping_method_form'), 'details-reload'
    );

    PayPalExpressAjax.addPleaseWait($('review-please-wait'));
</script>
