<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>
<?php
/* @var $this Mage_Sendfriend_Block_Send */
/**
 * Send to friend form
 *
 * @see Mage_Sendfriend_Block_Send
 */
?>

<script type="text/javascript">
//<![CDATA[
	i=0;
	var recipCount  = 1;
	var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
	function remove_recipient(i){
		$('recipients_name'+i).up(2).remove();
		recipCount--;
		if(recipCount<maxRecip && maxRecip != 0) {
			$('add_recipient_button').show();
			$('max_recipient_message').hide();
		}
		return false;
	}

	function add_recipient(){
		ul = $('recipients_options');
		var li_mail = Element.extend(document.createElement("li"));
		li_mail.addClassName('fields adjacent additional-row');
		li_mail.innerHTML = '<div class="field"><label for="recipients_name'+i+'" class="required"><em>*</em><?php $this->jsQuoteEscape(echo $this->__('Name')); ?><\/label><div class="input-box"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" title="<?php echo $this->__('Name') ?>" /><\/div><\/div>';
		li_mail.innerHTML += '<div class="field"><label for="recipients_email'+i+'" class="required"><em>*</em><?php echo $this->jsQuoteEscape($this->__('Email')); ?><\/label><div class="input-box"><input name="recipients[email][]" value="" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" title="<?php echo $this->__('Email') ?>" /><\/div><\/div>';
		li_mail.innerHTML += '<div class="remove-recipient"><a href="delete_email" title="<?php echo $this->jsQuoteEscape($this->__('Remove Recipient')); ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><?php echo $this->__('Remove Recipient') ?><\/a><\/div>';
		i++;
		recipCount++;
		if(recipCount>=maxRecip && maxRecip != 0) {
			$('add_recipient_button').hide();
			$('max_recipient_message').show();
		}

		ul.appendChild(li_mail);
	}
//]]>
</script>

<div class="grid-block">
	<h1><?php echo $this->__('Share By Email') ?></h1>

	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	
	<form action="<?php echo $this->getSendUrl() ?>" method="post" id="product_sendtofriend_form" class="stack-form">
		<?php echo $this->getBlockHtml('formkey')?>
		
		<div class="fieldset">
    		<h2 class="legend"><?php echo $this->__('Your Information') ?></h2>
    	
    		<ul class="form-list" id="sender_options">
    			<li class="fields adjacent">
    				<div class="field">
    					<label for="sender_name" class="required"><em>*</em><?php echo $this->__('Your Name') ?></label>
    					
    					<div class="input-box">
    						<input name="sender[name]" value="<?php echo $this->escapeHtml($this->getUserName()) ?>" id="sender_name" type="text" class="input-text required-entry" title="<?php echo $this->__('Your Name') ?>" />
    					</div>
    				</div>
    			
    				<div class="field">
    					<label for="sender_email" class="required"><em>*</em><?php echo $this->__('Your Email') ?></label>
    					
    					<div class="input-box">
    						<input name="sender[email]" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" id="sender_email" type="text" class="input-text required-entry validate-email" title="<?php echo $this->__('Your Email') ?>" />
    					</div>
    				</div>
    			</li>
    			
    			<li>
    				<label for="sender_message" class="required"><em>*</em><?php echo $this->__('Message') ?></label>
    				
    				<div class="input-box">
    					<textarea name="sender[message]" class="input-text required-entry" id="sender_message" rows="4" title="<?php echo $this->__('Message') ?>"><?php echo $this->escapeHtml($this->getMessage())?></textarea>
    				</div>
    			</li>
    		</ul>
    	</div>
	    
	    <div class="fieldset">
    		<h2 class="legend"><?php echo $this->__('Send To') ?></h2>
    		
    		<ul class="form-list" id="recipients_options">
    			<li class="fields adjacent">
    				<div class="field">
    					<label for="recipients_name" class="required"><em>*</em><?php echo $this->__('Name') ?></label>
    					
    					<div class="input-box">
    						<input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name" title="<?php echo $this->__('Name') ?>" />
    					</div>
    				</div>
    				
    				<div class="field">
    					<label for="recipients_email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
    					
    					<div class="input-box">
        					<input name="recipients[email][]" value="" id="recipients_email" type="text" class="input-text required-entry validate-email" title="<?php echo $this->__('Email') ?>" />
        				</div>
    				</div>
    			</li>
    		</ul>
		</div>
		
		<div class="buttons-set">
			<div id="max_recipient_message" style="display:none;">
				<?php if ($this->getMaxRecipients()): ?>
				  <p class="limit"><?php echo $this->__('Maximum %d email addresses allowed.', $this->getMaxRecipients()) ?></p>
				<?php endif; ?>
			</div>
			
			<?php if (1 < $this->getMaxRecipients()): ?>
				<p id="add_recipient_button">
				    <?php /* Magento */ ?>
				    <?php /*<button type="button" onclick="add_recipient();"><?php echo $this->__('Add Recipient') ?></button>*/ ?>
				    
				    <?php /* GravDept */ ?>
					<a class="button button-small button-subtle" href="#" onclick="add_recipient(); return false;"><?php echo $this->__('Add Recipient') ?></a>
				</p>
			<?php endif; ?>
			
			<div class="buttons-set">
    			<button type="submit" class="button <?php if (!$this->canSend()):?>disabled<?php endif ?>"<?php if (!$this->canSend()):?> disabled="disabled"<?php endif ?>><?php echo $this->__('Send Email') ?></button>
		    </div>
		</div>
	</form>
	
	<script type="text/javascript">
	//<![CDATA[
		var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
		productSendtofriendForm.submit = function() {
			if(this.validator.validate()) {
				this.form.submit();
			}
		}.bind(productSendtofriendForm);
	//]]>
	</script>
</div>
