<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2014 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.7
*/
?>

<?php $_product = $this->getProduct(); ?>

<?php if($_product->isSaleable()): ?>
	<div class="add-to-cart">
	    <?php
	    // GravDept:
	    // Moved to addquantity.phtml
	    ?>
	    <?php /*
	    <?php if(!$_product->isGrouped()): ?>
	    	<label for="qty"><?php echo $this->__('Qty:'); ?></label>
	    	<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty'); ?>" class="input-text qty" />
		<?php endif; ?>
		*/ ?>
		
		<button type="button" id="product-addtocart-button" class="button button-large" onclick="productAddToCartForm.submit(this)">
			<?php echo $this->__('Add to Cart'); ?>
		</button>
		
		<?php echo $this->getChildHtml('', true, true); ?>
	</div>
<?php endif; ?>
