<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<?php $_product = $this->getProduct() ?>

<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
	<li class="add-to-compare">
		<a class="button button-small button-subtle" href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add To Compare') ?></a>
		<?php /*<span><?php echo $this->__('View side-by-side with another item') ?></span>*/ ?>
	</li>
<?php endif; ?>