<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>

<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
	<a class="product-image primary zoom" rel="zoom-group" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>">
		<?php
		$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(360).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" />';
		echo $_helper->productAttribute($_product, $_img, 'image');
		?>
	</a>
<?php else: ?>
	<?php
	// GravDept:
	// No product image, use default.
	?>
	<a class="product-image primary">
		<?php
		$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(360).'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" />';
		echo $_helper->productAttribute($_product, $_img, 'image');
		?>
	</a>
<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): ?>
	<ul class="more-views">
		<?php foreach ($this->getGalleryImages() as $_image): ?>
			<li>
				<a class="product-image secondary zoom" rel="zoom-group" href="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile()) ?>" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
					<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(52, 52); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
				</a>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
