<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php if( $this->getCollection() && $this->count()): ?>
	<div id="dashboard-reviews" class="grid">
		<div class="grid_2 alpha">
			<h3><?php echo $this->__('My Reviews') ?></h3>
			<a class="button button-small button-subtle" href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All') ?></a>
		</div>
		
		<div class="grid_8 omega">
			<ol id="my-recent-reviews">
				<?php foreach ($this->getCollection() as $_review): ?>
					<li>
						<?php if($_review->getSum()): ?>
							<div class="ratings">
								<div class="rating-box">
									<div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
								</div>
							</div>
						<?php endif; ?>
						
						<a class="product-name" href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a>
					</li>
				<?php endforeach; ?>
			</ol>
		</div>
	</div>
<?php endif; ?>
