<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php if($this->getProductData()->getId()): ?>
	<h1><?php echo $this->__('My Review Details') ?></h1>
	
	<div id="product-review-view" class="grid">
		<div class="grid_2 alpha">
			<a class="product-image" href="<?php echo $this->getProductData()->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(130); ?>" alt="<?php echo $this->escapeHtml($this->getProductData()->getName()) ?>" /></a>
		</div>
		
		<div class="grid_5">
			<h2><a class="product-name" href="<?php echo $this->getProductData()->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductData()->getName()) ?></a></h2>
			
			<p class="written">
    			<?php if ($this->isReviewOwner()): ?>
    				<?php echo $this->__('You wrote on %s', $this->dateFormat($this->getReviewData()->getCreatedAt(), 'long')) ?>
    			<?php else: ?>
    				<?php echo $this->__('Written on %s', $this->dateFormat($this->getReviewData()->getCreatedAt(), 'long')) ?>
    			<?php endif; ?>
			</p>
			
			<div class="review-body">
				<?php echo nl2br($this->escapeHtml($this->getReviewData()->getDetail())) ?>
			</div>
		</div>
		
		<?php if( $this->getRating() && $this->getRating()->getSize()): ?>
			<div class="grid_3 omega">
				<?php if ($this->getRating() && $this->getRating()->getSize()): ?>
					<h3><?php echo $this->__('Average Rating') ?></h3>
					<?php echo $this->getReviewsSummaryHtml($this->getProductData()) ?>
				<?php endif; ?>
				
				<h3><?php echo ($this->isReviewOwner()) ? $this->__('My Rating') : $this->__('Rating'); ?></h3>
				
				<?php /* custom, one rating type only */ ?>
				<?php foreach ($this->getRating() as $_rating): ?>
					<?php if($_rating->getPercent()): ?>
						<div class="rating-box">
							<div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
						</div>
					<?php endif; ?>
				<?php endforeach; ?>
				
				<?php /*  // use for multiple rating types
				<table class="ratings-table">
					<?php foreach ($this->getRating() as $_rating): ?>
						<?php if($_rating->getPercent()): ?>
							<tr>
								<th><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></th>
								<td>
									<div class="rating-box">
										<div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
									</div>
								</td>
							</tr>
						<?php endif; ?>
					<?php endforeach; ?>
				</table>
				*/ ?>
			</div>
		<?php endif; ?>
	
	</div>
<?php endif; ?>
