<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<?php if ($this->getQuote()->hasVirtualItems()): ?>
	<h2><?php echo $this->__('Other items in your order') ?></h2>
	
	<table id="unavailable-shipping-table" class="data-table">
		<thead>
			<tr>
				<th><abbr title="<?php echo $this->__('Quantity') ?>"><?php echo $this->__('Qty.') ?></abbr></th>
				<th class="width-full"><?php echo $this->__('Product') ?></th>
			</tr>
		</thead>
		
		<tbody>
			<?php foreach ($this->getVirtualQuoteItems() as $_item): ?>
				<tr>
					<td class="a-center"><?php echo $_item->getQty() ?></td>
					<td><?php echo $this->getItemHtml($_item) ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<a href="<?php echo $this->getVirtualProductEditUrl() ?>"><?php echo $this->__('Edit Items') ?></a>
<?php endif; ?>
