<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php
// GravDept:
// Modified to place category title block above sidebar filter and product list.
// Derived functionality from: /template/catalog/category/view.phtml
// Some functionality moved to: /template/gravdept/catalog/category/title-banner.phtml
?>

<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
	<div class="catalog-static-block"><?php echo $this->getCmsBlockHtml() ?></div>
<?php elseif($this->isMixedMode()): ?>
	<div class="catalog-static-block"><?php echo $this->getCmsBlockHtml() ?></div>
	<?php echo $this->getProductListHtml() ?>
<?php else: ?>
	<?php echo $this->getProductListHtml() ?>
<?php endif; ?>
