<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.0
 */
?>

<p>
	<?php echo $this->getMethod()->getTitle() ?>
	
	<?php if($this->getInfo()->getAdditionalData()): ?>
		<?php if($this->getPayableTo()): ?><br /><?php echo $this->__('Make Check payable to: %s', $this->escapeHtml($this->getPayableTo())) ?><?php endif; ?>
		
		<?php if($this->getMailingAddress()): ?>
			<br />
			<?php echo Mage::helper('payment')->__('Send Check to:') ?>
			<br />
			<span class="checkmo-mailing-address">
				<?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
			</span>
		<?php endif; ?>
	<?php endif; ?>
</p>
