<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com All rights reserved.
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<?php $_order = $this->getOrder() ?>

<?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
    <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="button link-rss"><?php echo $this->__('Order Status RSS') ?></a>
<?php endif; ?>

<a href="<?php echo $this->getPrintUrl($_order) ?>" class="button link-print" onclick="this.target='_blank';"><?php echo $this->__('Print Order') ?></a>

<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
    <a href="<?php echo $this->getReorderUrl($_order) ?>" class="button link-reorder"><?php echo $this->__('Reorder') ?></a>
<?php endif ?>

<?php echo $this->getChildHtml(); ?>
