<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.9
 */
?>
<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */
?>
<?php if($this->getCurrencyCount()>1): ?>
    <div class="currency-selector switcher">
        <label for="select-currency"><?php echo $this->__('Currency') ?></label>
        
        <select id="select-currency" name="currency" onchange="setLocation(this.value)">
            <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
                <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                    <?php echo $_name ?> - <?php echo $_code ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>
